apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cbt-pvc
  annotations:
    snapshot.storage.kubernetes.io/change-block-tracking: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: csi-cbt-enabled
